title:            speesblog.com
description:      my external brain.
url:              http://speesblog.com/
baseurl:          ""
portfoliourl:     http://shelbyspees.com/

links:
  - name:         speesblog
    url:          /
  - name:         reading
    url:          /reading
  - name:         topics
    url:          /topics
  - name:         shelbyspees.com <i class="fa fa-external-link"></i>
    url:          http://shelbyspees.com/

highlighter:      pygments
permalink:        pretty
markdown:         kramdown
redcarpet:
  extensions:
    - smart

sass:
  sass_dir:       _sass

social:
  - name:         linkedin
    url:          http://linkedin.com/in/shelbyspees
    icon:         <i class="fa fa-linkedin-square"></i>
    external:     true
  - name:         github
    url:          https://github.com/shelbyspees
    icon:         <i class="fa fa-github-square"></i>
    external:     true
  - name:         twitter
    url:          https://twitter.com/speesbag/
    icon:         <i class="fa fa-twitter-square"></i>
    external:     true
  - name:         instagram
    url:          https://instagram.com/speesbag/
    icon:         <i class="fa fa-instagram"></i>
    external:     true
