title:            speesblog
description:      my external brain.
url:              http://speesbag.me
# signoff:          # Your name.
# disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
# facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
# google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

baseurl: 

links:
  - name:         posts
    url:          /
  - name:         about
    url:          /about
  - name:         reading
    url:          /reading
  - name:         topics
    url:          /topics
  - name:         portfolio
    url:          http://shelbyspees.me
highlighter:      pygments
permalink:        pretty
markdown:         kramdown
redcarpet:
  extensions:
    - smart

social:
  - name:         twitter
    url:          https://twitter.com/speesbag/
    icon:         <i class="fa fa-twitter-square"></i>
    external:     true
  - name:         instagram
    url:          https://instagram.com/speesbag/
    icon:         <i class="fa fa-instagram"></i>
    external:     true
  - name:         github
    url:          https://github.com/shelbyspees
    icon:         <i class="fa fa-github-square"></i>
    external:     true
