title:            speesblog
description:      Shelby writes things.
url:              http://speesblog.com/
baseurl:          ""
portfoliourl:     http://shelbyspees.com/

include: ["_pages"]

permalink: /:title/

links:
  - name:         speesblog
    url:          /
  - name:         reading
    url:          /reading
  - name:         topics
    url:          /topics

permalink:        pretty
markdown:         kramdown
kramdown:
  input: GFM

sass:
  sass_dir:       _sass

social:
  - name:         shelbyspees.com
    url:          http://shelbyspees.com/
    icon:         shelbyspees.com <i class="fa fa-external-link"></i>
    external:     true
  - name:         linkedin
    url:          http://linkedin.com/in/shelbyspees
    icon:         <i class="fa fa-linkedin-square"></i>
    external:     true
  - name:         github
    url:          https://github.com/shelbyspees
    icon:         <i class="fa fa-github-square"></i>
    external:     true
  - name:         twitter
    url:          https://twitter.com/speesbag/
    icon:         <i class="fa fa-twitter-square"></i>
    external:     true
  - name:         instagram
    url:          https://instagram.com/speesbag/
    icon:         <i class="fa fa-instagram"></i>
    external:     true
