title:            speesblog
description:      my external brain.
url:              http://shelbyspees.me/speesblog/
# signoff:          # Your name.
# disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
# facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
# google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

BASE_PATH: http://shelbyspees.me/speesblog
host: http://shelbyspees.me
baseurl: http://localhost:4000

servname: localhost:4000

links:
  - name:         blog
    url:          /speesblog
  - name:         about
    url:          /speesblog/about
  - name:         reading
    url:          /speesblog/reading
  - name:         portfolio
    url:          http://shelbyspees.me
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart

social:
  - name:         twitter
    url:          https://twitter.com/speesbag/
    icon:         <i class="fa fa-twitter-square fa-lg"></i>
    external:     true
  - name:         instagram
    url:          https://instagram.com/speesbag/
    icon:         <i class="fa fa-instagram fa-lg"></i>
    external:     true
  - name:         github
    url:          https://github.com/shelbyspees
    icon:         <i class="fa fa-github-square fa-lg"></i>
    external:     true
