# Site settings
title: speesblog
email: speesbag@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My publicly-viewable external brain.<br/>
  I don't pretend to be an expert on anything, I'm just really vain.
baseurl: "/speesblog" # the subpath of your site, e.g. /blog/
url: "http://shelbyspees.github.io/speesblog" # the base hostname & protocol for your site
twitter_username: speesbag
github_username:  shelbyspees

# Build settings
markdown: kramdown
